### PR TITLE
Use correct separator in keywords.txt

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE currently requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

### CODE REVIEW

**Comment by Floessie** [comment]
Hi Per,

> The Arduino IDE currently requires the use of a tab separator between the name and identifier.

Thanks for the pointer. I'll definitely integrate your PR. The statement above isn't completely true, tough: This is the "requirement" in the link you provided (highlighted by me):

> A tab **should** be used to separate each name from the identifier.

It's just a *should*...

> Without this tab the keyword is not highlighted.

This is definitely not true, at least with Arduino IDE 1.8.5 under Linux.

Best,
Flössie

**Comment by per1234** [comment]
I just verified that with the Linux ARM version of the Arduino IDE as well as the Windows version a true tab separator is indeed required.

The keywords as shown in the Arduino IDE when your version of the library is installed (stop and yield are highlighted because they are present in other keywords.txt files):
space_separator
The keywords as shown in the Arduino IDE when my version of the library is installed:
tab_separator
It seems strange that the Linux version of the IDE works differently in this respect than Windows or Linux ARM. Are you maybe using a modified version of the Arduino IDE, such as one installed via a package manager?

**Comment by Floessie** [comment]
You're right! 😳 I was fooled by other `keywords.txt` files, that highlighted some of my keywords. I should have digged deeper.

Thanks,
Flössie

**Comment by per1234** [comment]
Glad everything is cleared up now.

I have updated the wording of the library specification.

Note that in some future Arduino IDE release (probably 1.9.0), the tab requirement will be relaxed. I will update the specification at that time. However, it's not clear how far off that release is and (if history is any indication) people will still be using previous IDE versions for years after, especially since the new sketch preprocessor is likely to cause some breakage in the first releases.

**Comment by Floessie** [comment]
Absolutely. Thanks for the rewording. 👍 

Best,
Flössie

**Pull request merged**
